### ISSUE TITLE
Want to add some documentation

### ISSUE THREAD

**Issue by sb-decoder** [Zwnow/discogopher#2]
Want to add CODE_OF_CONDUCT.md and LICENSE.md

**Comment by Zwnow** [comment]
Sounds good to me

**Comment by sb-decoder** [comment]
@Zwnow, Hey need your full name for the license and email for CODE_OF_CONDUCT.md , can you provide those?

**Comment by Zwnow** [comment]
For sure, full name is Sven-Ole Timm, mail is svenotimm@gmail.com
